using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShillohHillsCollege.Core.DTO
{
    public class SessionDto
    {
        public Int64 Id { get; set; }
        public string Name { get; set; }
        public DateTime startDate { get; set; }
        public DateTime endDate { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public string DateModified { get; set; }
        public string ModifiedBy { get; set; }
    }

    public class AcademicTermDto
    {
        public Int64 Id { get; set; }
        public string Term { get; set; }
        public string Session { get; set; }
        public bool IsActive { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }

    public class AddAcademicTermDto
    {
        public string Term { get; set; }
        public string Session { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }

    public class AddSessionDto
    {
        public string SessionName { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public string submittedBy { get; set; }
    }

    public class AutoGeneratedRegNumberDto
    {
        public Int64 Id { get; set; }
        public Int64 RecId { get; set; }
        public string Category { get; set; }
        public DateTime? DateModified { get; set; }
    }

}
